<?php

/**
 *  @file
 *  Filename:   pinkglow_ds_fields.module
 *  Date    :   Sep 10, 2013
 */

/**
 * Implements hook_ds_fields_info
 */
function pinkglow_ds_fields_ds_fields_info($entity_type) {

  $fields = array();

  switch ($entity_type) {
    case 'node':
      $fields['pinkglow_ds_fields_linked_headline'] = array(
        'title' => 'Linked headline',
        'field_type' => DS_FIELD_TYPE_FUNCTION,
        'ui_limit' => array('puff|*'),
        'function' => 'pinkglow_ds_fields_linked_headline',
      );

      break;
  }

  return array($entity_type => $fields);
}

/**
 * Return linked puff headline.
 *
 * @param $context
 *   The entity context
 *
 * @return html
 */
function pinkglow_ds_fields_linked_headline($context) {
  
  $node = $context['entity'];
  
  $links = field_get_items('node', $node, 'field_l_nk');
  if (!empty($links)) {
    $link = array_shift($links);
    $url = $link['url'];
    
    return '<h2><a href="' . $url . '">' . $node->title . '</a></h2>';
  }
  else {
    return '<h2>' . $node->title . '</h2>';
  }
}